// Copyright (c) Alexandre Mutel. All rights reserved.
// Licensed under the BSD-Clause 2 license.
// See license.txt file in the project root for full license information.

// ReSharper disable InconsistentNaming
namespace RetroC64;

/// <summary>
/// Memory-mapped registers and associated enums for the Commodore 1541 disk drive.
/// Provides constants for VIA #1 (serial bus) and VIA #2 (drive control).
/// </summary>
/// <remarks>Source from https://sta.c64.org/cbm1541mem.html</remarks>
public static class C1541Registers
{
    // ========================
    // VIA #1 : Serial bus access ($1800-$180F)
    // ========================

    /// <summary>
    /// VIA #1 Port B ($1800). Serial bus control.
    /// See <see cref="VIA1PortB"/> for bit definitions.
    /// </summary>
    public const ushort VIA1_PORT_B = 0x1800;

    /// <summary>
    /// VIA #1 Port A ($1801). 
    /// Read to acknowledge interrupt generated by ATN IN going high.
    /// </summary>
    public const ushort VIA1_PORT_A = 0x1801;

    /// <summary>
    /// VIA #1 Port B Data Direction Register ($1802).
    ///
    /// Bit #x: 0 = Bit #x in port B can only be read; 1 = Bit #x in port B can be read and written.
    ///
    /// Default: $1A, 0b0001_1010.
    /// </summary>
    public const ushort VIA1_DATA_DIRECTION_B = 0x1802;

    /// <summary>
    /// VIA #1 Port A Data Direction Register ($1803).
    ///
    /// Default: $FF, 0b1111_1111.
    /// </summary>
    public const ushort VIA1_DATA_DIRECTION_A = 0x1803;

    /// <summary>
    /// VIA #1 Timer counter, low byte.
    /// Read low byte or write high byte to start/restart timer on underflow.
    /// </summary>
    public const ushort VIA1_TIMER_LOW = 0x1804;

    /// <summary>
    /// VIA #1 Timer counter, high byte.
    /// Read low byte or write high byte to start/restart timer on underflow.
    /// </summary>
    public const ushort VIA1_TIMER_HIGH = 0x1805;
    
    /// <summary>
    /// VIA #1 Timer latch, low byte $1806.
    /// Starting value of the timer.
    /// </summary>
    public const ushort VIA1_TIMER_LATCH_LOW = 0x1806;

    /// <summary>
    /// VIA #1 Timer latch, high byte $1807.
    /// Starting value of the timer.
    /// </summary>
    public const ushort VIA1_TIMER_LATCH_HIGH = 0x1807;

    /// <summary>
    /// VIA #1 Timer Control Register ($180B).
    /// See <see cref="VIA1TimerControl"/> for bit definitions.
    /// </summary>
    public const ushort VIA1_TIMER_CONTROL = 0x180B;

    /// <summary>
    /// VIA #1 Interrupt Status Register ($180D).
    /// See <see cref="VIA1InterruptFlags"/> for bit definitions.
    /// </summary>
    public const ushort VIA1_INTERRUPT_STATUS = 0x180D;

    /// <summary>
    /// VIA #1 Interrupt Control Register ($180E).
    /// See <see cref="VIA1InterruptEnable"/> for bit definitions.
    /// </summary>
    public const ushort VIA1_INTERRUPT_CONTROL = 0x180E;

    // ========================
    // VIA #2 : Drive control ($1C00-$1C0F)
    // ========================

    /// <summary>
    /// VIA #2 Port B ($1C00). Drive control.
    /// See <see cref="VIA2PortB"/> for bit definitions.
    /// </summary>
    public const ushort VIA2_PORT_B = 0x1C00;

    /// <summary>
    /// VIA #2 Port A ($1C01). Data byte read from / written to disk.
    /// </summary>
    public const ushort VIA2_PORT_A = 0x1C01;

    /// <summary>
    /// VIA #2 Port B Data Direction Register ($1C02).
    /// </summary>
    public const ushort VIA2_DATA_DIRECTION_B = 0x1C02;

    /// <summary>
    /// VIA #2 Port A Data Direction Register ($1C03).
    /// </summary>
    public const ushort VIA2_DATA_DIRECTION_A = 0x1C03;

    /// <summary>
    /// VIA #2 Timer counter, low byte.
    /// </summary>
    public const ushort VIA2_TIMER_LOW = 0x1C04;

    /// <summary>
    /// VIA #2 Timer counter, high byte.
    /// </summary>
    public const ushort VIA2_TIMER_HIGH = 0x1C05;

    /// <summary>
    /// VIA #2 Timer latch, low byte $1C06.
    /// </summary>
    public const ushort VIA2_TIMER_LATCH_LOW = 0x1C06;

    /// <summary>
    /// VIA #2 Timer latch, high byte $1C07.
    /// </summary>
    public const ushort VIA2_TIMER_LATCH_HIGH = 0x1C07;

    /// <summary>
    /// VIA #2 Timer Control Register ($1C0B).
    /// See <see cref="VIA2TimerControl"/> for bit definitions.
    /// </summary>
    public const ushort VIA2_TIMER_CONTROL = 0x1C0B;

    /// <summary>
    /// VIA #2 Auxiliary Control Register ($1C0C).
    /// See <see cref="VIA2AuxControl"/> for bit definitions.
    /// </summary>
    public const ushort VIA2_AUX_CONTROL = 0x1C0C;

    /// <summary>
    /// VIA #2 Interrupt Status Register ($1C0D).
    /// See <see cref="VIA2InterruptFlags"/> for bit definitions.
    /// </summary>
    public const ushort VIA2_INTERRUPT_STATUS = 0x1C0D;

    /// <summary>
    /// VIA #2 Interrupt Control Register ($1C0E).
    /// See <see cref="VIA2InterruptEnable"/> for bit definitions.
    /// </summary>
    public const ushort VIA2_INTERRUPT_CONTROL = 0x1C0E;

    // ========================
    // Enums for VIA #1 (Serial bus)
    // ========================

    /// <summary>
    /// Bit values for <see cref="C1541Registers.VIA1_PORT_B"/> (Serial bus control).
    /// </summary>
    [Flags]
    public enum VIA1PortB : byte
    {
        /// <summary>Bit 0: DATA IN; 0 = Low, 1 = High.</summary>
        DataIn = 1 << 0,

        /// <summary>Bit 1: DATA OUT; 0 = Low, 1 = High.</summary>
        DataOut = 1 << 1,

        /// <summary>Bit 2: CLOCK IN; 0 = Low, 1 = High.</summary>
        ClockIn = 1 << 2,

        /// <summary>Bit 3: CLOCK OUT; 0 = Low, 1 = High.</summary>
        ClockOut = 1 << 3,

        /// <summary>Bit 4: ATNA OUT; 1 = Enable automatic ATN acknowledge.</summary>
        AtnaOut = 1 << 4,

        /// <summary>Bits 5-6: Device number (see <see cref="VIA1DeviceNumber"/>).</summary>
        DeviceNumberMask = 0b11 << 5,

        /// <summary>Bit 7: ATN IN; 0 = Low, 1 = High.</summary>
        AtnIn = 1 << 7
    }

    /// <summary>
    /// Device number encoding for <see cref="C1541Registers.VIA1_PORT_B"/> (bits 5-6).
    /// </summary>
    public enum VIA1DeviceNumber : byte
    {
        /// <summary>Device #8 (%00).</summary>
        Device8 = 0,

        /// <summary>Device #9 (%01).</summary>
        Device9 = 0b01 << 5,

        /// <summary>Device #10 (%10).</summary>
        Device10 = 0b10 << 5,

        /// <summary>Device #11 (%11).</summary>
        Device11 = 0b11 << 5
    }

    /// <summary>
    /// VIA1 Timer Control Register bits (<see cref="C1541Registers.VIA1_TIMER_CONTROL"/>).
    /// </summary>
    [Flags]
    public enum VIA1TimerControl : byte
    {
        /// <summary>Bit 6 = 0: Stop timer.</summary>
        Stop = 0,

        /// <summary>Bit 6 = 1: Start timer.</summary>
        Start = 1 << 6
    }

    /// <summary>
    /// VIA1 Interrupt Status Register flags (<see cref="C1541Registers.VIA1_INTERRUPT_STATUS"/>).
    /// </summary>
    [Flags]
    public enum VIA1InterruptFlags : byte
    {
        /// <summary>Bit 1: ATN IN went high.</summary>
        AtnHigh = 1 << 1,

        /// <summary>Bit 6: Timer underflow occurred.</summary>
        TimerUnderflow = 1 << 6
    }

    /// <summary>
    /// VIA1 Interrupt Control Register bits (<see cref="C1541Registers.VIA1_INTERRUPT_CONTROL"/>).
    /// </summary>
    [Flags]
    public enum VIA1InterruptEnable : byte
    {
        /// <summary>Bit 1: Enable interrupts on ATN IN high (on write). An interrupt has been generated (on read).</summary>
        EnableAtnHigh = 1 << 1,

        /// <summary>
        /// Bit 7: Fill bit; copies bit 7 into selected mask bits.
        /// </summary>
        FillBitMask = 1 << 7
    }

    // ========================
    // Enums for VIA #2 (Drive control)
    // ========================

    /// <summary>
    /// Bit values for <see cref="C1541Registers.VIA2_PORT_B"/> (Drive control).
    /// </summary>
    [Flags]
    public enum VIA2PortB : byte
    {
        /// <summary>Bits 0-1: Head step sequence.</summary>
        StepDirectionMask = 0b11,

        /// <summary>Bit 2: Motor control; 0 = Off, 1 = On.</summary>
        Motor = 1 << 2,

        /// <summary>Bit 3: LED control; 0 = Off, 1 = On.</summary>
        Led = 1 << 3,

        /// <summary>Bit 4: Write protect status; 0 = Protected, 1 = Not protected.</summary>
        WriteProtect = 1 << 4,

        /// <summary>Bits 5-6: Data density (see <see cref="VIA2Density"/>).</summary>
        DensityMask = 0b11 << 5,

        /// <summary>Bit 7: 0 = SYNC mark, 1 = Data bytes.</summary>
        Sync = 1 << 7
    }

    /// <summary>
    /// VIA2 Data density values (<see cref="C1541Registers.VIA2_PORT_B"/> bits 5-6).
    /// </summary>
    public enum VIA2Density : byte
    {
        /// <summary>Lowest density (%00).</summary>
        Lowest = 0,

        /// <summary>Low density (%01).</summary>
        Low = 0b01 << 5,

        /// <summary>High density (%10).</summary>
        High = 0b10 << 5,

        /// <summary>Highest density (%11).</summary>
        Highest = 0b11 << 5
    }

    /// <summary>
    /// VIA2 Timer Control Register bits (<see cref="C1541Registers.VIA2_TIMER_CONTROL"/>).
    /// <code>
    /// +----------+---------------------------------------------------------+
    /// | Bits 7-6 |   Timer 1 Control:                                      |
    /// |          |     00 = Timed Interrupt when Timer 1 is loaded, no PB7 |
    /// |          |     01 = Continuous Interrupts, no PB7                  |
    /// |          |     10 = Timed Interrupt when Timer 1 is loaded,        |
    /// |          |          one-shot on PB7                                |
    /// |          |     11 = Continuous Interrupts, square-wave on PB7      |
    /// | Bit  5   |   Timer 2 Control: 0 = Timed Interrupt                  |
    /// |          |                    1 = Count Pulses on PB6              |
    /// | Bits 4-2 |   Shift Register Control:                               |
    /// |          |     000 = Disabled                                      |
    /// |          |     001 = Shift in under control of Timer 2             |
    /// |          |     010 = Shift in under control of Phi2                |
    /// |          |     011 = Shift in under control of ext. Clock          |
    /// |          |     100 = Shift out free-running at Timer 2 rate        |
    /// |          |     101 = Shift out under control of Timer 2            |
    /// |          |     110 = Shift out under control of Phi2               |
    /// |          |     111 = Shift out under control of ext. Clock         |
    /// | Bit  1   |   1 = enable latching PB                                |
    /// | Bit  0   |   1 = enable latching PA                                |
    /// +----------+---------------------------------------------------------+
    /// </code>>
    /// </summary>
    /// <remarks>
    /// Doc from http://unusedino.de/ec64/technical/aay/c1541/via2b.htm
    /// </remarks>
    [Flags]
    public enum VIA2TimerControl : byte
    {
        /// <summary>Enable latching PA</summary>
        EnableLatchingPA = 1 << 0,
        /// <summary>Enable latching PB</summary>
        EnableLatchingPB = 1 << 1,
        /// <summary>Shift Register Control mask (bits 2-4)</summary>
        ShiftRegisterControlMask = 0b111 << 2,
        /// <summary>Timer 2 Control: 0 = Timed Interrupt, 1 = Count Pulses on PB6</summary>
        CountPulsesOnPB6 = 1 << 5,
        /// <summary>Timer 1 Control mask (bits 6-7)</summary>
        Timer1ControlMask = 0b11 << 6,
    }

    public enum VIA2TimerControlInterrupt : byte
    {
        /// <summary>Timed Interrupt when Timer 1 is loaded, no PB7</summary>
        TimedInterruptWhenTimer1IsLoadedNoPB7 = 0,
        /// <summary>Continuous Interrupts, no PB7</summary>
        ContinuousInterruptsNoPB7 = 0b01 << 6,
        /// <summary>Timed Interrupt when Timer 1 is loaded, one-shot on PB7</summary>
        TimedInterruptWhenTimer1IsLoadedOneShotOnPB7 = 0b10 << 6,
        /// <summary>Continuous Interrupts, square-wave on PB7</summary>
        ContinuousInterruptsSquareWaveOnPB7 = 0b11 << 6,
    }

    /// <summary>
    /// VIA2 Auxiliary Control Register bits (<see cref="C1541Registers.VIA2_AUX_CONTROL"/>).
    /// </summary>
    [Flags]
    public enum VIA2AuxControl : byte
    {
        /// <summary>Bits 1-3: Attach Byte Ready line to V flag.</summary>
        ByteReadyToCpuVFlag = 0b111 << 1,

        /// <summary>Bits 5-7: Read head mode.</summary>
        HeadRead = 0b111 << 5,

        /// <summary>Bits 5-7: Write head mode.</summary>
        HeadWrite = 0b110 << 5
    }

    /// <summary>
    /// VIA2 Interrupt Status Register flags (<see cref="C1541Registers.VIA2_INTERRUPT_STATUS"/>).
    /// </summary>
    [Flags]
    public enum VIA2InterruptFlags : byte
    {
        /// <summary>Bit 6: Timer underflow occurred.</summary>
        TimerUnderflow = 1 << 6
    }

    /// <summary>
    /// VIA2 Interrupt Control Register bits (<see cref="C1541Registers.VIA2_INTERRUPT_CONTROL"/>).
    /// </summary>
    [Flags]
    public enum VIA2InterruptEnable : byte
    {
        /// <summary>Bit 6: Enable interrupts on timer underflow.</summary>
        EnableTimer = 1 << 6,

        /// <summary>
        /// Bit 7: Fill bit; copies bit 7 into selected mask bits.
        /// </summary>
        FillBit = 1 << 7
    }
}
